Repository googleapis/java-video-transcoder, pull requests merged in 2021-05, with the labels that each got.

#154 build(java): switch to release-please for release tagging
  .github/release-please.yml
  synth.metadata
Labels: api: transcoder, automerge, cla: yes, context: none

#155 chore: add enumeration data type to .repo-metadata.json
  .repo-metadata.json
Labels: api: transcoder, automerge, cla: yes

#156 chore: adding cloud-rad java xrefs
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: transcoder, automerge, cla: yes, context: full

#160 build(java): remove codecov action
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: transcoder, automerge, cla: yes, context: full

#161 chore: add changelog to cloud-rad
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: transcoder, automerge, cla: yes, context: full
